### ISSUE TITLE
do lint after generating code

### ISSUE THREAD

**Issue by kamijin-fanta** [akameco/s2s#113]
## Problem description:

- コードを自動生成した後、Lint等の処理を行いたい
  - 自動生成したコードがプロジェクトのLint設定と異なる場合がある

## Suggested solution:

- 1ファイルに対して複数ハンドラに対応させ、順番に適用する
- コードの自動生成を行った後、各種Lintを行うよう設定

設定の変更イメージ

```js
{
  handlerMapper: [
    {
      test: '*.ts',
      use: typescriptHandler,
    },
    {
      test: '*.ts',
      use: tslintHandler,
    },
  ]
}
```

**Comment by erukiti** [comment]
s2sとはちょっと違う仕組みで、同じような問題で格闘していたんですが、
babel-generate(transform) -> prettier -> tslint
っていう工程を踏むのが一番良いっぽい感じでした。

```typescript
import { Configuration, Linter } from 'tslint'

const linter = new Linter({ fix: true })
const generate = ast => {
  const { code } = babelGenerate(ast)
  const prettierOpts = {
    ...prettier.resolveConfig.sync(process.cwd()),
    parser: 'typescript'
  }
  const code2 = prettier.format(code, prettierOpts)
  const conf = Configuration.findConfiguration('tslint.json', inputFilename).results
  linter.lint(inputFilename, code2, conf)
  const { fixes } = linter.getResult()
  if (fixes.length > 0) {
    return fixes[fixes.length - 1].getRawLines()
  } else {
    return code2
  }
}
```

この場合でも、tslint fix が一回で終わるとは限らないので、fixesがある限りループして何回かfixするっていう処理が必要になるかもしれません。

**Comment by kamijin-fanta** [comment]
コードを読んでいると、 `afterHooks` なるものが有ったので、試しにプラグインを書いてみました。npmへの公開はまだやっていません。

https://github.com/kamijin-fanta/s2s-hook-tslint

@erukiti さんのコードを参考に実装しました。しかし、fixesのrawLinesは、該当fixesが適用される前のコードが格納されているようにみえるので、その点を修正しました。プラグインはs2s本体にPRで投げても良いです。

```ts
// s2s.config.js
const tslint = require('s2s-hook-tslint').default;

module.exports = {
  watch: './**/*.ts',
  plugins: [
    {
      test: /actionTypes.ts$/,
      plugin: ['s2s-action-types-ts', { removePrefix: 'src/' }],
    },
  ],
  prettier: false,
  afterHooks: [
    tslint({
      test: /\.(ts|tsx)/,
    })
  ]
}

```

afterhookのシグネチャは `(code: string, path: string) => string` という感じでした。自分は `tslint-plugin-prettier` からフォーマットを行っているので、prettierをfalseする事でデフォルトの標準のHookを無効にしました。

https://github.com/akameco/s2s/blob/4750cc1a8db9fab2356bea66a15fd139b0469da7/packages/s2s-cli/src/index.js#L52


---

以上を踏まえて、afterHookを用いた方法で良いんじゃないかと思いました。afterHook, prettierについてドキュメントに追記するとIssue閉じれるかなと思うのですが、良いですかね？

気付きとしては、

- afterHookに対してもtestが有っても良いかもしれない
- afterHookの適用状況をpluginsと同じように表示すると分かりやすい
- デフォルトのprettierHookの挙動がわかりにくかった
  - plugin/hookとして明示的に指定するほうが良いかもしれない

**Comment by akameco** [comment]
ちょっと経緯を説明すると、まさしくこのようなプラグイン適用後の共通の処理として、Hookという機能をはじめから用意してました。
ただ、Handlerの仕組みを導入前はjs以外処理する必要がなかったため事実上prettierだけあればいいという環境でした。で、何らかの明確な要望がない限りHookは実験的な機能という位置づけで、仕様を変更する可能性が大きいためあえてドキュメントにも書いてないという感じでした。

ただ、やはりTS対応など大きく変更が入り、今回tslintを使うという明確な目的があるので、ちょっとAPIをいじろうと思っています。
(他のhookがある場合、デフォルトのHookを無効する等)


> afterHookに対してもtest

基本的にhookは拡張子ベースだと思うので特に必要ないというのが今のところの考えです。

> afterHookの適用状況をpluginsと同じように表示すると分かりやすい

これは悩ましいですが、流石にうるさくなりすぎる気がします(1ファイル変更で7つのプラグインが動くなどがあるので)

> デフォルトのprettierHookの挙動がわかりにくかった

これは完全に申し訳ないです。上記の通りjsのみを扱うことを想定していたのでこんな感じになってます(直します)


> s2s-hook-tslint

作るのが早くてさすがです🎉 PR Welcomeです(もちろん自分でnpmにpublishしても全然大丈夫です)


> afterHook, prettierについてドキュメントに追記するとIssue閉じれるかなと思うのですが、良いですかね？

そうですね。その方針でいきましょう。

**Comment by akameco** [comment]
resolved #114
