### ISSUE TITLE
s2s-hook-tslintとoutputを渡すプラグインを同時に使用できない

### ISSUE THREAD

**Issue by kamijin-fanta** [akameco/s2s#123]
## Problem description 

背景

- s2s-hook-tslint
  - このhookは、tslintのAPIの都合上、lintを行う際にファイルへと書き込む
- s2s-cli
  - Hookを呼び出す `runHook` では、 `plugin.input` のパスを渡している  該当箇所: https://github.com/akameco/s2s/blob/f517ffa552ce1b76dbc1bc7a2f26a5800e63b5f2/packages/s2s-cli/src/handlers/handle-plugin.js#L38

起こった問題

- オプションで、inputと異なるoutputを渡すプラグインとs2s-hook-tslintを併用すると不具合が起きる
  - inputのファイルの内容がoutputで上書きされる

## Suggested solution 

1. runHookで、 `plugin.output` を渡す
  - hookが成果物へのLintで使用するAPIと考えると、 こちらのほうが整合性が有るかもしれない
2. 何らかの方法でs2s-hook-tslintをファイルに書き込まないように変更する

**Comment by akameco** [comment]
なぜfilepathが必要になったかというと処理するための拡張子が必要になっただけなのでinputをouputに変更しても問題はないと思われます。
ので、Suggested solutionの1に同意です。

**Comment by kamijin-fanta** [comment]
1で解決しました　ありがとうございます！
