### ISSUE TITLE
flow-faker@0.2.2 が存在しない

### ISSUE THREAD

**Issue by elzup** [akameco/s2s#158]
babel-plugin-s2s-initial-state-creater@^0.3.5 などが依存しているので npm install 時にエラーが起こる

エラー文

```
warning Lockfile has incorrect entry for "flow-faker@^0.2.2". Ignoring it.
Couldn't find any versions for "flow-faker" that matches "^0.2.2"
```

- module name: flow-faker
- module version: 0.2.2
- `node` version: v9.10.1
- `yarn` version: 1.7.0
  

**Do you want to request a _feature_ or report a _bug_?: bug

**What is the suggested solution?:**

publish される

**Comment by akameco** [comment]
なるほど。帰宅次第publishします

**Comment by akameco** [comment]
`flow-faker v0.2.4` としてPublishしました

**Comment by elzup** [comment]
確認できました。ありがとうございます
