### ISSUE TITLE
s2s-variable-initializing で const を使用するにはどうすればいいですか？

### ISSUE THREAD

**Issue by elzup** [akameco/s2s#72]
- module name:
babel-plugin-s2s-variable-initializing
https://github.com/akameco/s2s/tree/master/packages/babel-plugin-s2s-variable-initializing

- module version:
- `node` version:
v8.9.1

- `yarn` version:
yarn: 1.3.2

## What you did:
s2s のvariable-initializing を使っていて const で初期化生成しようとした。

## What happened:
const では出来なかった。
var や let では動作した。

**Comment by akameco** [comment]
これは、ASTの構造的な問題で、`const`では初期化できません。
なぜなら、パーサである`babylon`は`const`に初期値を期待するので初期値がない場合エラーになるからです(s2sはエラーをその無視します)。
一応前から問題自体は認識していてtwitterで言及してます。

> babylonでパース可能
> var a
> let a
> 
> 不可能
> const a
https://twitter.com/akameco/status/927989308035702784

> constは値がないとUnexpected tokenでパースすら出来ない
https://twitter.com/akameco/status/927989519193817088

現時点で取りうる解決作としては、`const`を使わずに、以下のようなハックを行う必要があります。


> s2sに型情報から初期化するプラグインがあるのだが、constだとパース出来ないのでletで書く→s2sで初期化→保存時にeslint --fixが走りconstにという最悪な手順になるのをどうにかしたい
https://twitter.com/akameco/status/927990795478560768

一応、constによる解決手段も模索しているのですが、現状優先度が高くないため、`s2s-variable-initializing`を使い`const`にしたい場合は、`let`を使い`eslint`で`const`に変換して下さい。


> パース不可能なコードに強制的に誤った変更を加えパース可能にし、それをFlowで強制的に修正するという邪悪な概念が浮かんだ
https://twitter.com/akameco/status/927988661035024384

**Comment by elzup** [comment]
僕も書いてみようとしたんですが const パースできないなってところまでわかって Issue 立てました。
そこまで重要度高くないので優先順位低くて大丈夫です。

**Comment by akameco** [comment]
了解です。`wantfix` ラベルを付けたので、このIssueは閉じます。
また、進展があったら再Openして下さい。
